;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				attila/line-cut
				attila/up-down-case-toggle
				c-electric-delete-forward
				c-electric-paren
				c-electric-star
				c-indent-line-or-region
				ess-smart-S-assign
				ess-smart-comma
				forward-sexp
				helm-show-kill-ring
				indent-for-tab-command
				indent-new-comment-line
				js2-line-break
				kill-region
				my/line-duplicate-below
				my/smarter-move-beginning-of-line
				my/yas-next-field-or-forward-sexp
				my/yas-previous-field-or-backward-sexp
				org-ctrl-c-ctrl-c
				org-delete-char
				org-force-self-insert
				org-metaleft
				org-self-insert-command
				org-yank
				tern-ac-dot-complete
				yaml-electric-backspace
				yaml-electric-dash-and-dot
				))

(setq mc/cmds-to-run-once
      '(
				helm-M-x
				helm-confirm-and-exit-minibuffer
				iedit-switch-to-mc-mode
				org-babel-tangle
				org-cycle
				))
