;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	forward-sexp
	helm-show-kill-ring
	indent-for-tab-command
	indent-new-comment-line
	js2-line-break
	kill-region
	my/smarter-move-beginning-of-line
	))

(setq mc/cmds-to-run-once
      '(
	))
