;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				forward-sexp
				helm-show-kill-ring
				indent-for-tab-command
				indent-new-comment-line
				js2-line-break
				kill-region
				my/line-duplicate-below
				my/smarter-move-beginning-of-line
				my/yas-next-field-or-forward-sexp
				my/yas-previous-field-or-backward-sexp
				org-self-insert-command
				tern-ac-dot-complete
				yaml-electric-backspace
				yaml-electric-dash-and-dot
				))

(setq mc/cmds-to-run-once
      '(
				helm-M-x
				iedit-switch-to-mc-mode
				))
