#+TITLE: MY ever imporoving Emacs configuration
#+AUTHOR: Attila V. Molnár
#+STARTUP: SHOWALL

* Unorthodox keybindings
** Rationale

I got the point of vim folks that overusing the modifier keys is inconvenient, however switching between insert and command to execute only one command... yes even for navigation (see [[https://github.com/abo-abo/avy][avy-mode]])
So what if I hit CapsLock and type a easily memorizable key-sequence without holding down the CapsLock or any of the modifier keys?
I tried it and worked pretty well.
Well I had to remap CapsLock to an otherwise expendable key: insert. (Seriously what is the real world use-case of that key, making ASCII art...)
however I will separate keybindings from the code to make it more configurable.

For this you should have an Xmodmap similar to this:

** Mnemonics

b for buffers
p for projects
i for insertion
l for line
m for manuals and docs
v for version control (magit)
s for search
x for I/O
ESC for exit

* Milestones

- [ ] implement js-import
- [ ] helm-dash
- [ ] helm-cider
- [ ] helm-pydoc
- [ ] helm-clojuredocs
- [ ] helm-commandlinefu maybe use [[https://github.com/ncrocfer/clf][clf]] instead.
- [ ] org mode .docx export
- [ ] paredit-mode
- [ ] Effective Blender-mode usage
- [ ] npm-mode
* Research
** atomic-chrome
It turned out that atomic-package only works on textareas, and most online text editors do not use them.
